name: dist

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - name: Install trunk
      uses: jetli/trunk-action@v0.1.0
      with:
        version: 'latest'
    - name: Build
      run: trunk build --release
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        cname: syn.cro.sh
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

permissions:
  contents: write
